// LOCALHOST
###
GET http://localhost:8080/contacts

### Get contacts by id
GET http://localhost:8080/contacts/65155c5c9ca4fbe2a5f6a287
###
GET http://localhost:8080/contacts/65155c5c9ca4fbe2a5f6a288
###
GET http://localhost:8080/contacts/65155c5c9ca4fbe2a5f6a289

### Create contact 
POST  http://localhost:8080/contacts HTTP/1.1 content-type: application/json

{
"firstName":"Lucas",
"lastName":"Kuma",
"email":"lucasKumah1@gmail.com",
"favoriteColor":"red", 
"birthday":"05/10/1991"
}

### PUT/update contact 
PUT http://localhost:8080/contacts/65155c5c9ca4fbe2a5f6a287  HTTP/1.1 content-type: application/json

{
    "firstName": "Gifty",
    "lastName": "Gbedemah",
    "email": "newtest@gmail.com",
    "favoriteColor": "Orange",
    "birthday": "9/5/2000"
}

### DELETE contact
DELETE http://localhost:8080/contacts/ HTTP/1.1




// PRODUCTION Deploy
###

###
GET https://cse341-wilson.onrender.com/contacts

###
GET https://cse341-wilson.onrender.com/contacts/650acc7d9a9a0652c4b9305e

###
GET https://cse341-wilson.onrender.com/contacts/650acc7d9a9a0652c4b9305f

###
GET https://cse341-wilson.onrender.com/contacts/650acc7d9a9a0652c4b93060

